namespace Munarium.Wire;

using System.Text.Json.Serialization;
using Munarium.Evidence;

/// <summary>
/// The JSON shape of the wire contract.
/// </summary>
/// <remarks>
/// Snake case and source-generated metadata, so the JSON the server emits is the JSON the
/// specification describes (<c>claim_id</c>, <c>as_of</c>, <c>top_k</c>) and the serializer needs no
/// reflection at runtime.
/// </remarks>
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower)]
[JsonSerializable(typeof(WireSessionCreated))]
[JsonSerializable(typeof(WireTurnRequest))]
[JsonSerializable(typeof(WireTurnResponse))]
[JsonSerializable(typeof(WireSession))]
[JsonSerializable(typeof(WireSessionClosed))]
[JsonSerializable(typeof(WireRunbookApply))]
[JsonSerializable(typeof(WireAppliedRunbook))]
[JsonSerializable(typeof(WireRunbook))]
[JsonSerializable(typeof(WireRunbookList))]
[JsonSerializable(typeof(WireHealth))]
[JsonSerializable(typeof(WireVersionHead))]
[JsonSerializable(typeof(WireVersion))]
[JsonSerializable(typeof(WireVersionLineage))]
[JsonSerializable(typeof(WireVersionRequest))]
[JsonSerializable(typeof(WireContextSection))]
[JsonSerializable(typeof(WireContextRequest))]
[JsonSerializable(typeof(WireComposedContext))]
[JsonSerializable(typeof(WireClaimProposal))]
[JsonSerializable(typeof(WireClaimOutcome))]
[JsonSerializable(typeof(WireClaimCandidate))]
[JsonSerializable(typeof(WireClaimBatchRequest))]
[JsonSerializable(typeof(WireClaimBatchOutcome))]
[JsonSerializable(typeof(WireFinding))]
[JsonSerializable(typeof(WireStoredFinding))]
[JsonSerializable(typeof(WireFindingList))]
[JsonSerializable(typeof(WireSnapshot))]
[JsonSerializable(typeof(WireResolvedClaim))]
[JsonSerializable(typeof(WireAnchor))]
[JsonSerializable(typeof(WireDigest))]
[JsonSerializable(typeof(WirePromise))]
[JsonSerializable(typeof(WireCounter))]
[JsonSerializable(typeof(WireEntity))]
[JsonSerializable(typeof(WireAnchorLock))]
[JsonSerializable(typeof(WirePromiseRegistration))]
[JsonSerializable(typeof(WireAnchorRelease))]
[JsonSerializable(typeof(WirePromiseFulfilment))]
[JsonSerializable(typeof(WireAnchorList))]
[JsonSerializable(typeof(WirePromiseList))]
[JsonSerializable(typeof(WireCounterRecording))]
[JsonSerializable(typeof(WireCounterList))]
[JsonSerializable(typeof(WireProblem))]
[JsonSerializable(typeof(WireFact))]
[JsonSerializable(typeof(WireFactSlice))]
[JsonSerializable(typeof(WireSourceReference))]
[JsonSerializable(typeof(WireProvenanceEnvelope))]
[JsonSerializable(typeof(WireRetrievedChunk))]
[JsonSerializable(typeof(WireSearchQuery))]
[JsonSerializable(typeof(WireSearchResult))]
[JsonSerializable(typeof(WireShape))]
[JsonSerializable(typeof(WireShapeList))]
[JsonSerializable(typeof(WireSourceIngest))]
[JsonSerializable(typeof(WireAccessTokenRequest))]
[JsonSerializable(typeof(WireAccessToken))]
[JsonSerializable(typeof(WireAccessTokenAudit))]
[JsonSerializable(typeof(WireAccessTokenAuditList))]
[JsonSerializable(typeof(WireAuthoringPattern))]
[JsonSerializable(typeof(WireAuthoringPatternList))]
[JsonSerializable(typeof(WireAuthoringDraftRequest))]
[JsonSerializable(typeof(WireAuthoringAnswers))]
[JsonSerializable(typeof(WireAuthoringDraft))]
[JsonSerializable(typeof(WireAuthoringDraftList))]
[JsonSerializable(typeof(WireDraftValidation))]
[JsonSerializable(typeof(WireAuthoringDraftRemoved))]
[JsonSerializable(typeof(WireAuthoringApplied))]
[JsonSerializable(typeof(WireAuthoringBundle))]
[JsonSerializable(typeof(WireIngestedSource))]
[JsonSerializable(typeof(WireSourceInfo))]
[JsonSerializable(typeof(WireSourceList))]
[JsonSerializable(typeof(WireIndexVersionList))]
[JsonSerializable(typeof(WireIndexManifest))]
[JsonSerializable(typeof(WireSealEvidenceRequest))]
[JsonSerializable(typeof(WireSealResponse))]
[JsonSerializable(typeof(WireEvidenceGrant))]
[JsonSerializable(typeof(WireEvidenceAccess))]
[JsonSerializable(typeof(WireEvidenceAccessList))]
[JsonSerializable(typeof(WireEvidenceRows))]
[JsonSerializable(typeof(WireEvidenceCommit))]
[JsonSerializable(typeof(WireEvidencePurge))]
[JsonSerializable(typeof(WireEvidenceBytesUpload))]
[JsonSerializable(typeof(WireEvidenceLegalHold))]
[JsonSerializable(typeof(EvidenceManifest))]
[JsonSerializable(typeof(WireIndexVersion))]
[JsonSerializable(typeof(WireIndexBuild))]
[JsonSerializable(typeof(WireIndexActivation))]
[JsonSerializable(typeof(WireEnvelopeQuery))]
[JsonSerializable(typeof(WireEnvelopeResolution))]
[JsonSerializable(typeof(WireTurnProfileEvent))]
[JsonSerializable(typeof(WireTurnLayerStartEvent))]
[JsonSerializable(typeof(WireTurnLayerSourceEvent))]
[JsonSerializable(typeof(WireTurnLayerCompleteEvent))]
[JsonSerializable(typeof(WireTurnCoverageEvent))]
[JsonSerializable(typeof(WireTurnComposeEvent))]
[JsonSerializable(typeof(WireTurnModelEvent))]
[JsonSerializable(typeof(WireTurnExpansionEvent))]
[JsonSerializable(typeof(WireTurnProbeEvent))]
[JsonSerializable(typeof(WireTurnSelectionEvent))]
[JsonSerializable(typeof(WireTurnRetrievalEvent))]
[JsonSerializable(typeof(WireTurnMergeEvent))]
[JsonSerializable(typeof(WireTurnCompletionEvent))]
[JsonSerializable(typeof(WireTurnVerifyEvent))]
public sealed partial class WireJson : JsonSerializerContext;
